name: Deploy Develop
on:
  push:
    branches:
      - dev

jobs:
  Firebase-Functions-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version: "20.x"

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Build Backend
        run: pnpm build
        working-directory: ./services/backend

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.7.1
        continue-on-error: false
        with:
          args: deploy --only firestore,functions --force
        env:
          GCP_SA_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          PROJECT_ID: early-dev-73f4d
        working-directory: ./services/backend
