name: Deploy Production
on:
  push:
    branches:
      - main
    paths:
      - "services/api/**"
      - "packages/**"

jobs:
  Firebase-Functions-Deploy:
    runs-on: ubuntu-latest

    env: # Added environment variables here
      FIREBASE_PROJECT_ID: early-prod-dddac
      FIREBASE_STORAGE_BUCKET: early-prod-dddac.appspot.com

    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version: "20.x"

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm install

      - name: Authenticate to Firebase
        run:
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_PROD }}" >
          $HOME/gcp-key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS:
            ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_PROD }}

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
        run: npx firebase deploy
        working-directory: ./services/api
